---
- hosts: localhost
  connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mariadb_root_password: ""
    mariadb_admin_password: "admin"
    prometheus_version: "2.36.0"
    mysqld_exporter_version: "0.13.0"

  tasks:
    - name: Installation de MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Configuration de MariaDB
      template:
        src: my.cnf.j2
        dest: /etc/mysql/my.cnf

    - name: Configure for root
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
     
    - name: Restart mariaDB
      service:
        name: mariadb
        state: restarted

    - name: Creation d'utilisateur admin pour MariaDB
      mysql_user:
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: root
        login_password: "{{ mariadb_root_password }}"
        name: admin
        password: "{{ mariadb_admin_password }}"
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Execution du script SQL
      mysql_db:
        login_unix_socket: /run/mysqld/mysqld.sock
        login_user: admin
        login_password: "{{ mariadb_admin_password }}"
        name: ma_base
        state: import
        target: schema.sql
  
    - name: Installation de Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus.tar.gz"
    
    - name: Unarchive Prometheus
      unarchive:
        src: "/tmp/prometheus.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Configuration de Prometheus pour surveiller MariaDB
      copy:
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'mariadb'
              static_configs:
                - targets: ['localhost:9104']
        dest: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"

    - name: Telechargement de l'exporteur MariaDB
      get_url:
        url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/mysqld_exporter.tar.gz"

    - name: Extraction de l'exporteur MariaDB
      unarchive:
        src: "/tmp/mysqld_exporter.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Configuration de l'exporteur MariaDB
      copy:
        content: |
          DATA_SOURCE_NAME='admin:{{ mariadb_admin_password }}@(localhost:3306)/'
        dest: "/opt/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/.env"

    - name: Ajout du repo de Grafana
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present

    - name: Installation de Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Demarage du service grafana
      systemd:
        name: grafana-server
        enabled: yes
        state: started

    - name: Demarrage de l'exporteur MariaDB
      systemd:
        name: mysqld_exporter
        enabled: yes
        state: started
        exec_start_pre: "/bin/chmod +x /opt/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter"
        exec_start: "/opt/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter --config.my-cnf=/opt/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/.env"
